name = "MyExample"
uuid = "d5ea3eb5-8f23-4545-bbb4-15e086127766"
authors = ["Iga Szczesniak"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
